### ISSUE TITLE
Research Publishing Command Tools

### ISSUE THREAD

**Issue by flyingzumwalt** [CodeForPhilly/ipfs-switchboard#3]
Look up popular publishing tools like npm, git, etc and gather observations about how they work.

**Comment by flyingzumwalt** [comment]
@munadm

**Comment by munadm** [comment]
There are some pretty cool ideas behind the different popular publishing  managers out there. 

All the well known ones (apt, npm, nuget, whatever they use in JavaLand) all follow the dependency tree format where a initial required root nodes is laid out by a parsable file (think of package.json) and then do a classic DFS of all the child dependencies of each root node. Many policies are being evolved to make this tree smarter and flatter. For example, apt employs the explicit versioning where you package needs to describe all the versions of the child dependencies you need straight off the bat while npm does actually tries to readjust the tree based on the full picture of all the dependency. 

This is an important topic to explore when we will start developing our own publishing algorithm. Will profiles that have a cryptographic hash of their files need to show how files that have been cited from (think research papers with citation lists)? How about hashes of new versions of the data, how would we provide users a good experience when they want to know which version of the data has been cited?

As stated by the ticket here are some of the articles I've read to figure out some under-the-hood magic behind dependency management

 - Medium article on package manager patterns, good for understanding the dependency tree - https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527#.a1j3ftrr5
 - Smallest and easiest explanation I found about how apt works through dependency cycle problem - https://www.debian.org/doc/debian-policy/ch-relationships.html
 - npmv3 and dependency cycle - https://docs.npmjs.com/how-npm-works/npm3
